version: "3"
services:
  nginx:
    image: nginx:1.21.4
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./config:/etc/nginx/conf.d
      - appdata:/var/www
  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - appdata:/var/www
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sait
    volumes:
      - ./mysql:/var/lib/mysql
volumes:
  appdata:
