version: "3"
services:
  nginx:
    image: nginx:1.21.4
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./config:/etc/nginx/conf.d
      - appdata:/var/www
  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - appdata:/var/www
volumes:
  appdata:
